type Foo = { className: number };

type Element<T extends {}> = JSX.Element & Methodize<T>;
type Methodize<T extends {}> = {
  [K in keyof T]-?: (value: T[K] | undefined) => Element<T>;
};
type ComponentOf<ElementName extends keyof JSX.IntrinsicElements> = (
  ...children: JSX.Element[]
) => Element<JSX.IntrinsicElements[ElementName]>;

export declare const A: ComponentOf<"a">;
export declare const Abbr: ComponentOf<"abbr">;
export declare const Address: ComponentOf<"address">;
export declare const Area: ComponentOf<"area">;
export declare const Article: ComponentOf<"article">;
export declare const Aside: ComponentOf<"aside">;
export declare const Audio: ComponentOf<"audio">;
export declare const B: ComponentOf<"b">;
export declare const Base: ComponentOf<"base">;
export declare const Bdi: ComponentOf<"bdi">;
export declare const Bdo: ComponentOf<"bdo">;
export declare const Blockquote: ComponentOf<"blockquote">;
export declare const Body: ComponentOf<"body">;
export declare const Br: ComponentOf<"br">;
export declare const Button: ComponentOf<"button">;
export declare const Canvas: ComponentOf<"canvas">;
export declare const Caption: ComponentOf<"caption">;
export declare const Cite: ComponentOf<"cite">;
export declare const Code: ComponentOf<"code">;
export declare const Col: ComponentOf<"col">;
export declare const Colgroup: ComponentOf<"colgroup">;
export declare const Data: ComponentOf<"data">;
export declare const Datalist: ComponentOf<"datalist">;
export declare const Dd: ComponentOf<"dd">;
export declare const Del: ComponentOf<"del">;
export declare const Details: ComponentOf<"details">;
export declare const Dfn: ComponentOf<"dfn">;
export declare const Dialog: ComponentOf<"dialog">;
export declare const Dir: ComponentOf<"dir">;
export declare const Div: ComponentOf<"div">;
export declare const Dl: ComponentOf<"dl">;
export declare const Dt: ComponentOf<"dt">;
export declare const Em: ComponentOf<"em">;
export declare const Embed: ComponentOf<"embed">;
export declare const Fieldset: ComponentOf<"fieldset">;
export declare const Figcaption: ComponentOf<"figcaption">;
export declare const Figure: ComponentOf<"figure">;
export declare const Font: ComponentOf<"font">;
export declare const Footer: ComponentOf<"footer">;
export declare const Form: ComponentOf<"form">;
export declare const Frame: ComponentOf<"frame">;
export declare const Frameset: ComponentOf<"frameset">;
export declare const H1: ComponentOf<"h1">;
export declare const H2: ComponentOf<"h2">;
export declare const H3: ComponentOf<"h3">;
export declare const H4: ComponentOf<"h4">;
export declare const H5: ComponentOf<"h5">;
export declare const H6: ComponentOf<"h6">;
export declare const Head: ComponentOf<"head">;
export declare const Header: ComponentOf<"header">;
export declare const Hgroup: ComponentOf<"hgroup">;
export declare const Hr: ComponentOf<"hr">;
export declare const Html: ComponentOf<"html">;
export declare const I: ComponentOf<"i">;
export declare const Iframe: ComponentOf<"iframe">;
export declare const Img: ComponentOf<"img">;
export declare const Input: ComponentOf<"input">;
export declare const Ins: ComponentOf<"ins">;
export declare const Kbd: ComponentOf<"kbd">;
export declare const Label: ComponentOf<"label">;
export declare const Legend: ComponentOf<"legend">;
export declare const Li: ComponentOf<"li">;
export declare const Link: ComponentOf<"link">;
export declare const Main: ComponentOf<"main">;
export declare const Map: ComponentOf<"map">;
export declare const Mark: ComponentOf<"mark">;
export declare const Marquee: ComponentOf<"marquee">;
export declare const Menu: ComponentOf<"menu">;
export declare const Meta: ComponentOf<"meta">;
export declare const Meter: ComponentOf<"meter">;
export declare const Nav: ComponentOf<"nav">;
export declare const Noscript: ComponentOf<"noscript">;
export declare const Ol: ComponentOf<"ol">;
export declare const Optgroup: ComponentOf<"optgroup">;
export declare const Option: ComponentOf<"option">;
export declare const Output: ComponentOf<"output">;
export declare const P: ComponentOf<"p">;
export declare const Param: ComponentOf<"param">;
export declare const Picture: ComponentOf<"picture">;
export declare const Pre: ComponentOf<"pre">;
export declare const Progress: ComponentOf<"progress">;
export declare const Q: ComponentOf<"q">;
export declare const Rp: ComponentOf<"rp">;
export declare const Rt: ComponentOf<"rt">;
export declare const Ruby: ComponentOf<"ruby">;
export declare const S: ComponentOf<"s">;
export declare const Samp: ComponentOf<"samp">;
export declare const Script: ComponentOf<"script">;
export declare const Section: ComponentOf<"section">;
export declare const Select: ComponentOf<"select">;
export declare const Slot: ComponentOf<"slot">;
export declare const Small: ComponentOf<"small">;
export declare const Source: ComponentOf<"source">;
export declare const Span: ComponentOf<"span">;
export declare const Strong: ComponentOf<"strong">;
export declare const Style: ComponentOf<"style">;
export declare const Sub: ComponentOf<"sub">;
export declare const Summary: ComponentOf<"summary">;
export declare const Sup: ComponentOf<"sup">;
export declare const Table: ComponentOf<"table">;
export declare const Tbody: ComponentOf<"tbody">;
export declare const Td: ComponentOf<"td">;
export declare const Template: ComponentOf<"template">;
export declare const Textarea: ComponentOf<"textarea">;
export declare const Tfoot: ComponentOf<"tfoot">;
export declare const Th: ComponentOf<"th">;
export declare const Thead: ComponentOf<"thead">;
export declare const Time: ComponentOf<"time">;
export declare const Title: ComponentOf<"title">;
export declare const Tr: ComponentOf<"tr">;
export declare const Track: ComponentOf<"track">;
export declare const U: ComponentOf<"u">;
export declare const Ul: ComponentOf<"ul">;
export declare const Video: ComponentOf<"video">;
export declare const Wbr: ComponentOf<"wbr">;

export {};
