import React from "https://cdn.skypack.dev/react";

const elementProto = new Proxy(
  {},
  {
    get(_, prop) {
      return function (value) {
        this.props[prop] = value;
        return this;
      };
    },
  }
);

export function El(type) {
  return (...children) => {
    const o = React.createElement(type, {}, ...children);
    return globalThis.Object.setPrototypeOf(
      { ...o, props: { ...o.props } },
      elementProto
    );
  };
}
export const A = El("a");
export const Abbr = El("abbr");
export const Address = El("address");
export const Area = El("area");
export const Article = El("article");
export const Aside = El("aside");
export const Audio = El("audio");
export const B = El("b");
export const Base = El("base");
export const Bdi = El("bdi");
export const Bdo = El("bdo");
export const Big = El("big");
export const Blockquote = El("blockquote");
export const Body = El("body");
export const Br = El("br");
export const Button = El("button");
export const Canvas = El("canvas");
export const Caption = El("caption");
export const Cite = El("cite");
export const Code = El("code");
export const Col = El("col");
export const Colgroup = El("colgroup");
export const Data = El("data");
export const Datalist = El("datalist");
export const Dd = El("dd");
export const Del = El("del");
export const Details = El("details");
export const Dfn = El("dfn");
export const Dialog = El("dialog");
export const Div = El("div");
export const Dl = El("dl");
export const Dt = El("dt");
export const Em = El("em");
export const Embed = El("embed");
export const Fieldset = El("fieldset");
export const Figcaption = El("figcaption");
export const Figure = El("figure");
export const Footer = El("footer");
export const Form = El("form");
export const H1 = El("h1");
export const H2 = El("h2");
export const H3 = El("h3");
export const H4 = El("h4");
export const H5 = El("h5");
export const H6 = El("h6");
export const Head = El("head");
export const Header = El("header");
export const Hgroup = El("hgroup");
export const Hr = El("hr");
export const Html = El("html");
export const I = El("i");
export const Iframe = El("iframe");
export const Img = El("img");
export const Input = El("input");
export const Ins = El("ins");
export const Kbd = El("kbd");
export const Keygen = El("keygen");
export const Label = El("label");
export const Legend = El("legend");
export const Li = El("li");
export const Link = El("link");
export const Main = El("main");
export const Map = El("map");
export const Mark = El("mark");
export const Menu = El("menu");
export const Menuitem = El("menuitem");
export const Meta = El("meta");
export const Meter = El("meter");
export const Nav = El("nav");
export const Noindex = El("noindex");
export const Noscript = El("noscript");
export const Object = El("object");
export const Ol = El("ol");
export const Optgroup = El("optgroup");
export const Option = El("option");
export const Output = El("output");
export const P = El("p");
export const Param = El("param");
export const Picture = El("picture");
export const Pre = El("pre");
export const Progress = El("progress");
export const Q = El("q");
export const Rp = El("rp");
export const Rt = El("rt");
export const Ruby = El("ruby");
export const S = El("s");
export const Samp = El("samp");
export const Slot = El("slot");
export const Script = El("script");
export const Section = El("section");
export const Select = El("select");
export const Small = El("small");
export const Source = El("source");
export const Span = El("span");
export const Strong = El("strong");
export const Style = El("style");
export const Sub = El("sub");
export const Summary = El("summary");
export const Sup = El("sup");
export const Table = El("table");
export const Template = El("template");
export const Tbody = El("tbody");
export const Td = El("td");
export const Textarea = El("textarea");
export const Tfoot = El("tfoot");
export const Th = El("th");
export const Thead = El("thead");
export const Time = El("time");
export const Title = El("title");
export const Tr = El("tr");
export const Track = El("track");
export const U = El("u");
export const Ul = El("ul");
export const Var = El("var");
export const Video = El("video");
export const Wbr = El("wbr");
export const Webview = El("webview");
export const Svg = El("svg");
export const Animate = El("animate");
export const AnimateMotion = El("animateMotion");
export const AnimateTransform = El("animateTransform");
export const Circle = El("circle");
export const ClipPath = El("clipPath");
export const Defs = El("defs");
export const Desc = El("desc");
export const Ellipse = El("ellipse");
export const FeBlend = El("feBlend");
export const FeColorMatrix = El("feColorMatrix");
export const FeComponentTransfer = El("feComponentTransfer");
export const FeComposite = El("feComposite");
export const FeConvolveMatrix = El("feConvolveMatrix");
export const FeDiffuseLighting = El("feDiffuseLighting");
export const FeDisplacementMap = El("feDisplacementMap");
export const FeDistantLight = El("feDistantLight");
export const FeDropShadow = El("feDropShadow");
export const FeFlood = El("feFlood");
export const FeFuncA = El("feFuncA");
export const FeFuncB = El("feFuncB");
export const FeFuncG = El("feFuncG");
export const FeFuncR = El("feFuncR");
export const FeGaussianBlur = El("feGaussianBlur");
export const FeImage = El("feImage");
export const FeMerge = El("feMerge");
export const FeMergeNode = El("feMergeNode");
export const FeMorphology = El("feMorphology");
export const FeOffset = El("feOffset");
export const FePointLight = El("fePointLight");
export const FeSpecularLighting = El("feSpecularLighting");
export const FeSpotLight = El("feSpotLight");
export const FeTile = El("feTile");
export const FeTurbulence = El("feTurbulence");
export const Filter = El("filter");
export const ForeignObject = El("foreignObject");
export const G = El("g");
export const Image = El("image");
export const Line = El("line");
export const LinearGradient = El("linearGradient");
export const Marker = El("marker");
export const Mask = El("mask");
export const Metadata = El("metadata");
export const Mpath = El("mpath");
export const Path = El("path");
export const Pattern = El("pattern");
export const Polygon = El("polygon");
export const Polyline = El("polyline");
export const RadialGradient = El("radialGradient");
export const Rect = El("rect");
export const Stop = El("stop");
export const Switch = El("switch");
export const Symbol = El("symbol");
export const Text = El("text");
export const TextPath = El("textPath");
export const Tspan = El("tspan");
export const Use = El("use");
export const View = El("view");
